# Generated by Django 4.2.1 on 2023-05-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('direccion_origen', models.CharField(max_length=100)),
                ('direccion_destino', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
