# Generated by Django 4.2.1 on 2023-05-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourier', '0002_solicitud_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
