# Generated by Django 4.2.1 on 2023-05-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourier', '0003_alter_solicitud_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='por enviar', max_length=100),
        ),
    ]
