# Generated by Django 4.2.2 on 2023-06-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourier', '0004_solicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='Preparacion', max_length=100),
        ),
    ]
