# Generated by Django 4.2.2 on 2023-06-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCourier', '0006_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
